version: 2
updates:
  # npm (JavaScript) の依存関係
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'

  # GitHub Actions の依存関係
  - package-ecosystem: 'github-actions'
    directory: '/.github/workflows'
    schedule:
      interval: 'weekly'
